export enum SkinCareFeature {
  AntiAge = 1,
  Antibacterial = 2,
  Cleansing = 3,
  Firming = 4,
  Moisturizing = 5,
  Solvent = 6,
  Perfuming = 7,
  Antioxidant = 8,
  Preservative = 9,
  Soothing = 11,
  Emulsifying = 12,
  OilControlling = 13,
  CellCommunicating = 14,
  SkinIdentical = 15,
  Buffering = 16,
  Exfoliating = 17,
  ViscosityControlling = 18,
  Emollient = 19,
  SkinBrightening = 20,
  UvProtection = 21,
  Colorant = 22
}
